name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Compile:
    runs-on: ubuntu-latest
    uses: actions/checkout@v4
    steps:
      - run: echo "Compile check!"

  Test:
    runs-on: ubuntu-latest
    uses: actions/checkout@v4
    steps:
      - run: echo "Test check!"